"use client";
import {FormEvent,useEffect,useState} from "react";

const roles=[['svetlana','Svetlana de Monte Carlo'],['richard','Richard Darling'],['anastasia','Anastasia Ferrari'],['jean-claude','Jean-Claude Bērziņš'],['kevin','Kevin von Whatever']];
const eur=(c:number=0)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(c/100);
const telegramStatus=(status:string)=>status==='not_required'?'No Telegram recipient linked':status;
const field=(form:HTMLFormElement,name:string)=>String(new FormData(form).get(name)??'');

export default function Dashboard({studentName,bot,sheet,github}:{studentName:string;bot:string;sheet:string;github:string}){
  const [role,setRole]=useState('svetlana'),[state,setState]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const load=async(selectedRole=role)=>{setState(null);const r=await fetch(`/api/state?actor=${encodeURIComponent(selectedRole)}`,{cache:'no-store'});setState(await r.json())};
  useEffect(()=>{load(role)},[role]);
  async function post(url:string,body:any){setBusy(true);setMessage('');try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,actor:role})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(x.duplicate?'Already decided; totals were not changed.':'Saved successfully.');await load(role)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const submitSale=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;post('/api/transactions',{kind:'sale',reference:field(f,'reference'),customer:field(f,'customer'),project:field(f,'project'),description:field(f,'description'),amount:field(f,'amount'),richard:Number(field(f,'richard')),anastasia:Number(field(f,'anastasia')),jeanClaude:Number(field(f,'jeanClaude'))})};
  const submitExpense=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=e.currentTarget;post('/api/transactions',{kind:'expense',reference:field(f,'reference'),description:field(f,'description'),category:field(f,'category'),amount:field(f,'amount'),allocation:field(f,'allocation')})};
  const d=state?.dashboard;
  return <main>
    <header><div><p className="eyebrow">FRIENDS INCLUDED LTD · FINANCE DESK</p><h1>Every friendship accounted for.</h1><p>Sales, expenses, approvals and the cost of convincing affection — in one reliable ledger.</p></div><div className="identity"><span>Prepared by</span><strong>{studentName}</strong></div></header>
    <nav><label>Demonstration role<select value={role} onChange={e=>setRole(e.target.value)}>{roles.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select></label><div><a href={bot?`https://t.me/${bot}`:'#'}>Telegram bot</a><a href={sheet}>Google Sheet</a><a href={github}>GitHub</a></div></nav>
    {message&&<p className="message">{message}</p>}
    {role==='svetlana'&&<section><div className="sectionTitle"><p>Live position</p><h2>Financial dashboard</h2></div>{!d?<p>{state?.error??'Loading…'}</p>:<div className="metrics">
      {(['A','B'] as const).map(p=><article key={p}><span>Project {p}</span><strong>{eur(d.projects[p].result)}</strong><dl><div><dt>Income</dt><dd>{eur(d.projects[p].income)}</dd></div><div><dt>Commission</dt><dd>{eur(d.projects[p].commission)}</dd></div><div><dt>Expenses</dt><dd>{eur(d.projects[p].expenses)}</dd></div></dl></article>)}
      <article className="dark"><span>Company result</span><strong>{eur(d.company.result)}</strong><dl><div><dt>Overhead</dt><dd>{eur(d.company.overhead)}</dd></div><div><dt>Awaiting allocation</dt><dd>{eur(d.company.awaiting)}</dd></div><div><dt>All expenses</dt><dd>{eur(d.company.expenses)}</dd></div></dl></article>
      <article><span>Commission earned</span><strong>{eur(d.earned.richard+d.earned.anastasia+d.earned.jeanClaude)}</strong><dl><div><dt>Richard</dt><dd>{eur(d.earned.richard)}</dd></div><div><dt>Anastasia</dt><dd>{eur(d.earned.anastasia)}</dd></div><div><dt>Jean-Claude</dt><dd>{eur(d.earned.jeanClaude)}</dd></div></dl></article>
    </div>}</section>}
    <section className="two"><div><div className="sectionTitle"><p>Record income</p><h2>New sale</h2></div><form onSubmit={submitSale}><input name="reference" placeholder="Reference e.g. S01" required/><input name="customer" placeholder="Customer" required/><select name="project"><option value="A">Project A · Respectable Relatives</option><option value="B">Project B · Drunk University Friends</option></select><textarea name="description" placeholder="Description" required/><input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount €" required/><div className="split"><label>Richard %<input name="richard" type="number" min="0" max="100" defaultValue="50"/></label><label>Anastasia %<input name="anastasia" type="number" min="0" max="100" defaultValue="30"/></label><label>Jean-Claude %<input name="jeanClaude" type="number" min="0" max="100" defaultValue="20"/></label></div><button disabled={busy}>Submit sale</button></form></div>
      <div><div className="sectionTitle"><p>Record spending</p><h2>New expense</h2></div><form onSubmit={submitExpense}><input name="reference" placeholder="Reference e.g. E01" required/><textarea name="description" placeholder="Description" required/><select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select><input name="amount" type="number" min="0.01" step="0.01" placeholder="Amount €" required/><select name="allocation"><option value="A">Project A</option><option value="B">Project B</option><option>Company overhead</option></select><button disabled={busy}>Submit expense</button></form></div></section>
    {role==='svetlana'&&<section><div className="sectionTitle"><p>Manager decisions</p><h2>Approval queue</h2></div><div className="queue">
      {state?.sales?.filter((s:any)=>s.status==='Pending approval').map((s:any)=><form className="decision" key={s.reference} onSubmit={e=>{e.preventDefault();const f=e.currentTarget;post('/api/decisions',{kind:'sale',reference:s.reference,richard:Number(field(f,'richard')),anastasia:Number(field(f,'anastasia')),jeanClaude:Number(field(f,'jeanClaude'))})}}><div><b>{s.reference} · {s.customer}</b><p>{eur(s.amount_cents)} · Project {s.project} · {s.description}</p></div><input name="richard" defaultValue={s.proposed_richard_pct}/><input name="anastasia" defaultValue={s.proposed_anastasia_pct}/><input name="jeanClaude" defaultValue={s.proposed_jean_claude_pct}/><button>Approve sale</button></form>)}
      {state?.expenses?.filter((e:any)=>e.status==='Awaiting allocation').map((x:any)=><form className="decision" key={x.reference} onSubmit={e=>{e.preventDefault();post('/api/decisions',{kind:'expense',reference:x.reference,allocation:field(e.currentTarget,'allocation')})}}><div><b>{x.reference} · {eur(x.amount_cents)}</b><p>{x.description} · Proposed {x.proposed_allocation}</p></div><select name="allocation" defaultValue={x.proposed_allocation}><option value="A">Project A</option><option value="B">Project B</option><option>Company overhead</option></select><button>Confirm allocation</button></form>)}
      {!state?.sales?.some((s:any)=>s.status==='Pending approval')&&!state?.expenses?.some((x:any)=>x.status==='Awaiting allocation')&&<p>Nothing is waiting for Svetlana.</p>}
    </div><div className="managerTools"><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget;post('/api/employees/link',{employee:field(f,'employee'),telegramUserId:field(f,'telegramUserId'),telegramChatId:field(f,'telegramChatId')})}}><h3>Telegram employee link</h3><select name="employee">{roles.slice(1).map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</select><input name="telegramUserId" placeholder="Telegram user ID" required/><input name="telegramChatId" placeholder="Chat ID (optional until /start)"/><button>Save link</button></form><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget;post('/api/retry',{kind:field(f,'kind'),reference:field(f,'reference'),target:field(f,'target')})}}><h3>Retry failed delivery</h3><select name="kind"><option value="sale">Sale</option><option value="expense">Expense</option></select><input name="reference" placeholder="Reference" required/><select name="target"><option value="sheet">Google Sheets</option><option value="telegram">Telegram</option></select><button>Retry</button></form></div></section>}
    <section><div className="sectionTitle"><p>Audit trail</p><h2>Transaction records</h2></div><div className="tableWrap"><table><thead><tr><th>Ref</th><th>Type / owner</th><th>Description</th><th>Amount</th><th>Proposal → final</th><th>Status</th><th>Sheets</th><th>Telegram</th></tr></thead><tbody>
      {state?.sales?.map((s:any)=><tr key={s.reference}><td>{s.reference}</td><td>Sale · {s.salesperson}</td><td>{s.customer}<small>{s.description}</small></td><td>{eur(s.amount_cents)}</td><td>{s.proposed_richard_pct}/{s.proposed_anastasia_pct}/{s.proposed_jean_claude_pct} → {s.approved_richard_pct==null?'—':`${s.approved_richard_pct}/${s.approved_anastasia_pct}/${s.approved_jean_claude_pct}`}</td><td>{s.status}</td><td>{s.sheet_sync_status}</td><td>{telegramStatus(s.notification_status)}</td></tr>)}
      {state?.expenses?.map((x:any)=><tr key={x.reference}><td>{x.reference}</td><td>Expense · {x.reporter}</td><td>{x.description}<small>{x.category}</small></td><td>{eur(x.amount_cents)}</td><td>{x.proposed_allocation} → {x.final_allocation??'—'}</td><td>{x.status}</td><td>{x.sheet_sync_status}</td><td>{telegramStatus(x.notification_status)}</td></tr>)}
    </tbody></table></div></section>
    <footer><b>How to use</b><span>Select a role, submit a permitted transaction, then switch to Svetlana to approve or correct it. Telegram uses the formats shown by /help.</span></footer>
  </main>
}
